### ISSUE TITLE
пропало соединение,  в чем ошибка? 

### ISSUE THREAD

**Issue by SergiiMytakii** [Glajik/Song-Book#3]
хотя раньше мой запрос к серверу работал,  сейчас почему то перестал.  Выдает ошибку:

 E/cs50: com.android.volley.NoConnectionError: java.net.UnknownHostException: Unable to resolve host "song-book-289222.ew.r.appspot.com": No address associated with hostname

Код я не менял.  ЧТо это может быть?

**Comment by Glajik** [comment]
Проверил, вроде работает.

**Comment by SergiiMytakii** [comment]
да,  проблема была в эмуляторе телефона.  Разобрался.

**Comment by Glajik** [comment]
ок
